### ISSUE TITLE
Practica 2_Tablas de verdad

### ISSUE THREAD

**Issue by A-Lorely-Z** [SistemasTecTlaxiaco/actividad-8-practica-de-tablas-de-verdad-lennin-s-team-1as#2]
[Practica 2 Unidad 3 Matematicas.pdf](https://github.com/user-attachments/files/17551939/Practica.2.Unidad.3.Matematicas.pdf)

**Comment by UsuarioIncognito** [comment]
Portada:25/25
Procedimiento/Desarrollo:25/25
Figuras, Ilustraciones y Fotografías:25/25
Resultados y conclusiones:25/25
Total:100/100

Califica: Adal Eliel Bautista Sanjuan

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
